# 1.Bag of Words

Mètode per treure diferents **característiques** d’un text. 

Utilitzat per entrenaments per tal de crear **llista de vocabulari.**

No es important l’ordre sinó les paraules úniques **que hi apareixen**. 



Apart del processament de llenguatge natural també es utilitzat en **recuperació d’informació en textos** i **classificació d’aquests**.
	
El resultat s’obté amb **vectors**, **poc òptim** si volem llistats de vocabulari extensos.


**El procés es el següent:**

1.	Agafem text 
2.	Netejar text

3.	Tokenizació ( eliminació de les paraules stopword com signes puntuació)

ignore = ['a', "the", "is"] 

4.	Generació de vocabulari
5.	Generació de vectors

cleaned_text : ['joe', 'waited', 'for', 'train'] 
Word List for Document :['for', 'joe', 'train', 'waited']

Joe waited for the train
Vector = [1. 1. 1. 1.]



Importació llibreries

In [1]:
import numpy
import re

frases a processar

In [2]:
allsentences = ["chandler waited for the car", "The bus was late","Phoebe and Joe took the train"]

neteja de les frases

In [3]:
def word_extraction(sentence):
    ignore = ['a', "the", "is"]
    words = re.sub("[^\w]", " ", sentence).split() #separa per paraules
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text

Tokenize ordenació en una llista

In [4]:
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)

    words = sorted(list(set(words)))
    return words

gerenració funció Bag of words

In [5]:
def generate_bow(allsentences):
    vocabulary = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocabulary));

    for sentence in allsentences:
        words = word_extraction(sentence)
        #cracio de vectors llargada de llista vocabulary
        bag_vector = numpy.zeros(len(vocabulary))
        for w in words:
            for i, word in enumerate(vocabulary):
                if word == w:
                    bag_vector[i] += 1

        print("{0} \n{1}\n".format(sentence, numpy.array(bag_vector)))


In [6]:
generate_bow(allsentences)

Word List for Document 
['and', 'bus', 'car', 'chandler', 'for', 'joe', 'late', 'phoebe', 'the', 'took', 'train', 'waited', 'was'] 

chandler waited for the car 
[0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]

The bus was late 
[0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]

Phoebe and Joe took the train 
[1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0.]



**Referencies:**

An introduction to Bag of Words and how to code it in Python for NLP
https://www.freecodecamp.org/news/an-introduction-to-bag-of-words-and-how-to-code-it-in-python-for-nlp-282e87a9da04/

Bag-of-words model - Wikipedia
https://en.wikipedia.org/wiki/Bag-of-words_model